name: Deploy Shared Library and Executable

on:
  push:
    branches:
      - deploy
  workflow_run:
    workflows: ["Merge Dev to Main and Deploy Branches"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set TERM variable
        run: echo "TERM=xterm" >> $GITHUB_ENV

      - name: Mark Repository as Safe
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
    
      - name: Install Dependencies
        run: |
          sudo apt-get update
          xargs -a .apt-dependencies sudo apt-get install -y

      - name: Launch make re
        run: make re
        timeout-minutes: 3

      - name: Create Tag
        id: create_tag
        run: |
            MAJOR=$(( ${{ github.run_number }} / 100 + 1))
            MINOR=$(( (${{ github.run_number }} / 10) % 10 ))
            PATCH=$(( ${{ github.run_number }} % 10 ))
            TAG="v${MAJOR}.${MINOR}.${PATCH}"
            echo "TAG=$TAG" >> $GITHUB_ENV
            git tag $TAG
            git push origin $TAG

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          files: |
            CamShit
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
